import Head from "next/head";
import { useState } from "react";
import ButtonBottom from "../elements/ButtonBottom";
import Breadcrumb from "./Breadcrumb";
import Footer from "./Footer";
import Header from "./Header";
import MobileMenu from "./MobileMenu";
import HeaderLifeStyle from "../lifestyle/HeaderLifeStyle";

const Layout = ({
  children,
  parent,
  sub,
  subChild,
  noBreadcrumb,
  headerStyle,
}) => {
  const [isToggled, setToggled] = useState(false);
  const toggleClick = () => {
    setToggled(!isToggled);
    isToggled
      ? document.querySelector("body").classList.remove("mobile-menu-active")
      : document.querySelector("body").classList.add("mobile-menu-active");
  };

  return (
    <>
      <Head>
        <title>Club Bambu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&family=Spartan:wght@300;400;500;600;700&display=swap');
        </style>
      </Head>

      {isToggled && (
        <div className="body-overlay-1" onClick={toggleClick}></div>
      )}

      <Header
        headerStyle={headerStyle}
        isToggled={isToggled}
        toggleClick={toggleClick}
        HeaderLifeStyle={HeaderLifeStyle}
      />
      <MobileMenu isToggled={isToggled} toggleClick={toggleClick} HeaderLifeStyle={HeaderLifeStyle}/>
      <main className="main">
        <Breadcrumb
          parent={parent}
          sub={sub}
          subChild={subChild}
          noBreadcrumb={noBreadcrumb}
        />
        {children}
      </main>

      {/* <Footer /> */}
      <div className="mb-8 "></div>
      {/* <ButtonBottom /> */}
    </>
  );
};

export default Layout;
